require("../../resource/Project/1_createProject.js")()
require("../../resource/Project/2_getAllProject.js")()
require("../../resource/Project/3_getAProject.js")()
require("../../resource/Project/4_updateAProject.js")()
require("../../resource/Project/5_deleteProject.js")()
